# Generated by Django 5.2.3 on 2025-06-22 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveGotham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='save-gotham/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('BR', 'Batarang'), ('GG', 'Grapnel Gun'), ('BM', 'Batmobile'), ('BP', 'Batplane')], max_length=2)),
            ],
        ),
    ]
