# Generated by Django 5.2.3 on 2025-06-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegotham',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
    ]
