# Generated by Django 5.2.3 on 2025-06-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batman', '0002_savegotham_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savegotham',
            name='type',
            field=models.CharField(choices=[('Batarang', 'Batarang'), ('Grapnel Gun', 'Grapnel Gun'), ('Batmobile', 'Batmobile'), ('Batplane', 'Batplane')], max_length=100),
        ),
    ]
