# Generated by Django 5.2.3 on 2025-06-23 09:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batman', '0003_alter_savegotham_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1/5', '1/5: Not Worthy'), ('2/5', '2/5: Poor'), ('3/5', '3/5: Average'), ('4/5', '4/5: Good'), ('5/5', '5/5: Best')], max_length=100)),
                ('comment', models.TextField(default='No comment provided.')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='batman.savegotham')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description provided.')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_ability', to='batman.savegotham')),
            ],
        ),
        migrations.CreateModel(
            name='VillainAlliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alliance_type', models.CharField(choices=[('Temporary', 'Temporary alliance'), ('Long-term', 'Long-term partnership'), ('Rivalry', 'Friendly rivalry')], max_length=50)),
                ('description', models.TextField(default='No description provided.')),
                ('villains', models.ManyToManyField(related_name='alliances', to='batman.savegotham')),
            ],
        ),
    ]
