# Generated by Django 5.2.3 on 2025-06-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batman', '0004_candidatereviews_specialability_villainalliances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villainalliances',
            old_name='villains',
            new_name='hero',
        ),
        migrations.RenameField(
            model_name='villainalliances',
            old_name='name',
            new_name='villian',
        ),
        migrations.RemoveField(
            model_name='villainalliances',
            name='alliance_type',
        ),
    ]
