# Generated by Django 5.2.3 on 2025-06-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batman', '0005_rename_villains_villainalliances_hero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villainalliances',
            old_name='hero',
            new_name='heros',
        ),
    ]
