# Generated by Django 5.2.3 on 2025-06-23 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batman', '0006_rename_hero_villainalliances_heros'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroesAlliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villian', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description provided.')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('heroes', models.ManyToManyField(related_name='alliances', to='batman.savegotham')),
            ],
        ),
        migrations.DeleteModel(
            name='VillainAlliances',
        ),
    ]
