# Generated by Django 5.2.3 on 2025-06-23 11:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batman', '0007_heroesalliances_delete_villainalliances'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateReviews',
            new_name='CandidateReview',
        ),
        migrations.RenameModel(
            old_name='HeroesAlliances',
            new_name='HeroesAlliance',
        ),
    ]
